name: Calculadora CI with Maven
on :
  push:
    branches : ["main"]
  pull_request:
    branches : ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./kalkulagailua
    steps:
      - name: Descargar el código del repositorio
        uses: actions/checkout@v4
      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '25'
      - name: Compilar y ejecutar tests de la Calculadora
        run: mvn clean pac
      - name: Guardar la Calculadora compilada
        uses: actions/upload-artifact@v4
        with:
          name: calculadora-app
          path: target/*.jar
            
